server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 668939       # ← 改成 Navicat 里 root 的密码
  jpa:
    hibernate:
      ddl-auto: update       # 自动建表
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

